### ISSUE TITLE
Remover o local.properties e adicionar à lista de exclusão.

### ISSUE THREAD

**Issue by Knitter** [SaulPT/ProjetoAPP#1]
1) Com o Android Studio fechado, removam o local.properties;
2) Façam commit da remoção de modo a ficar registada a alteração;
3) Editem o .gitignore e adicionem uma linha com o nome do ficheiro a ignorar: local.properties;
4) Façam commit desta alteração para que, a partir deste momento, não sejam verificadas alterações no ficheiro.

A partir daqui não precisam mexer mais neste ficheiro (local.properties).

**Comment by SaulPT** [comment]
Isso era como estava inicialmente (feito pelo Android studio).
Mas os meus colegas disseram que dava erro do género "sdk not found"
Apenas fiz isto numa tentativa de resolver isso. Mas não foi discutido sequer


---- Sérgio Lopes escreveu ----


  1.  Com o Android Studio fechado, removam o local.properties;
  2.  Façam commit da remoção de modo a ficar registada a alteração;
  3.  Editem o .gitignore e adicionem uma linha com o nome do ficheiro a ignorar: local.properties;
  4.  Façam commit desta alteração para que, a partir deste momento, não sejam verificadas alterações no ficheiro.

A partir daqui não precisam mexer mais neste ficheiro (local.properties).

-

**Comment by SaulPT** [comment]
Penso já ter percebido. O commit da eliminação do ficheiro não pode ser feito no Android studio? 
(eu tenho feito sempre no studio)

**Comment by Knitter** [comment]
O IDE vai estar sempre a tentar criar o ficheiro enquanto estiver aberto, precisa dele para funcionar. Mesmo que seja apenas este commit, façam com o IDE fechado.

**Comment by SaulPT** [comment]
ok ty :) fixed
